# Generated by Django 5.2.5 on 2025-09-05 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_arenda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arenda',
            options={'ordering': ['-created_at'], 'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренды'},
        ),
    ]
