# Generated by Django 5.2 on 2025-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_arenda_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenda',
            name='game_count',
            field=models.PositiveIntegerField(default=6, verbose_name='Количество игр в аренде'),
        ),
        migrations.AlterField(
            model_name='arenda',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название аренды'),
        ),
    ]
