# Generated by Django 5.2.5 on 2025-09-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_arenda_game_count_alter_arenda_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('date_event', models.DateField(verbose_name='Дата мероприятия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
