# Generated by Django 5.2 on 2025-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('order_type', models.CharField(choices=[('buy', 'Купить'), ('rent', 'Аренда')], max_length=10, verbose_name='Тип заказа')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('arenda', models.ManyToManyField(blank=True, to='core.arenda', verbose_name='Выбранные аренды')),
                ('products', models.ManyToManyField(blank=True, to='core.product', verbose_name='Выбранные товары')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
