# Generated by Django 5.2 on 2025-09-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='games_for_rent',
            field=models.ManyToManyField(blank=True, related_name='order_games_for_rent', to='core.product', verbose_name='Игры для аренды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='arenda',
            field=models.ManyToManyField(blank=True, related_name='order_arenda', to='core.arenda', verbose_name='Выбранные аренды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='order_products', to='core.product', verbose_name='Выбранные товары'),
        ),
    ]
