# Generated by Django 5.2 on 2025-09-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_games_for_rent_alter_order_arenda_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
