# Generated by Django 5.2 on 2025-09-16 10:49

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Изображение', null=True, blank=True),
        ),
        migrations.RunSQL(
            "UPDATE core_product SET image = main_image WHERE main_image IS NOT NULL;",
            reverse_sql="UPDATE core_product SET main_image = image WHERE image IS NOT NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_product DROP COLUMN main_image;",
            reverse_sql="ALTER TABLE core_product ADD COLUMN main_image varchar(100);"
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Изображение'),
        ),
    ]
