# Generated by Django 5.2 on 2025-09-16 10:49

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Изображение'),
        ),
    ]
