# Generated by Django 5.2 on 2025-09-16 11:03

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fix_product_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/additional/', verbose_name='Дополнительное изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение товара',
                'verbose_name_plural': 'Дополнительные изображения товаров',
            },
        ),
    ]
