# Generated by Django 5.2 on 2025-09-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_product_image_product_main_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вид игры')),
            ],
            options={
                'verbose_name': 'Вид игры',
                'verbose_name_plural': 'Виды игр',
            },
        ),
        migrations.CreateModel(
            name='PlayerAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50, verbose_name='Возраст игроков')),
            ],
            options={
                'verbose_name': 'Возраст игрока',
                'verbose_name_plural': 'Возрасты игроков',
            },
        ),
        migrations.CreateModel(
            name='PlayerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество игроков')),
            ],
            options={
                'verbose_name': 'Количество игроков',
                'verbose_name_plural': 'Количество игроков',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AddField(
            model_name='product',
            name='game_kit',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Комплект игры'),
        ),
        migrations.AddField(
            model_name='product',
            name='game_rules',
            field=models.JSONField(blank=True, null=True, verbose_name='Правила игры'),
        ),
        migrations.AddField(
            model_name='product',
            name='game_types',
            field=models.ManyToManyField(blank=True, to='core.gametype', verbose_name='Виды игры'),
        ),
        migrations.AddField(
            model_name='product',
            name='player_ages',
            field=models.ManyToManyField(blank=True, to='core.playerage', verbose_name='Возрасты игроков'),
        ),
        migrations.AddField(
            model_name='product',
            name='player_counts',
            field=models.ManyToManyField(blank=True, to='core.playercount', verbose_name='Количество игроков'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='core.size', verbose_name='Размеры'),
        ),
    ]
