# Generated by Django 5.2 on 2025-09-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_gametype_playerage_playercount_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='product',
            name='game_rules',
            field=models.TextField(blank=True, null=True, verbose_name='Правила игры'),
        ),
    ]
