# Generated by Django 5.2 on 2025-09-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_product_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='game_kit',
            field=models.TextField(blank=True, null=True, verbose_name='Комплект игры'),
        ),
    ]
