# Generated by Django 5.2 on 2025-09-17 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_productimage_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_players', models.PositiveIntegerField(verbose_name='Минимальное количество игроков')),
                ('max_players', models.PositiveIntegerField(verbose_name='Максимальное количество игроков')),
                ('min_game_count', models.PositiveIntegerField(verbose_name='Минимальное количество игр')),
                ('max_game_count', models.PositiveIntegerField(verbose_name='Максимальное количество игр')),
            ],
            options={
                'verbose_name': 'Количество игроков для аренды',
                'verbose_name_plural': 'Количество игроков для аренды',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='date_event',
            field=models.DateTimeField(verbose_name='Дата и время мероприятия'),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/additional/', verbose_name='Дополнительное изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='core.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение новости',
                'verbose_name_plural': 'Дополнительные изображения новостей',
            },
        ),
        migrations.AddField(
            model_name='arenda',
            name='ranges',
            field=models.ManyToManyField(blank=True, to='core.playerrange', verbose_name='Диапазоны игроков и игр'),
        ),
    ]
