# Generated by Django 5.2 on 2025-09-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_additionalproducts_alter_playerrange_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalproducts',
            options={'verbose_name': 'Дополнительное к товарам', 'verbose_name_plural': 'Дополнительные к товарам'},
        ),
        migrations.CreateModel(
            name='AdditionalProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='additional_product_images/additional/', verbose_name='Дополнительное изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('additional_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='core.additionalproducts', verbose_name='Допы к товару')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение допов товара',
                'verbose_name_plural': 'Дополнительные изображения допов товара',
            },
        ),
    ]
