# Generated by Django 5.2 on 2025-09-21 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_additionalproducts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата заказа'),
        ),
    ]
