# Generated by Django 5.2 on 2025-09-21 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Время заказа'),
        ),
    ]
