# Generated by Django 5.2 on 2025-09-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_products',
            field=models.ManyToManyField(blank=True, related_name='order_additional_products', to='core.additionalproducts', verbose_name='Дополнительные товары'),
        ),
    ]
