# Generated by Django 5.2 on 2025-09-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_order_additional_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameKitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted_text', models.CharField(help_text="Текст, который будет отображаться крупным шрифтом (например, '46x46см')", max_length=50, verbose_name='Выделенный текст')),
                ('normal_text', models.CharField(help_text="Текст, который будет отображаться обычным шрифтом (например, 'игровое поле')", max_length=200, verbose_name='Обычный текст')),
            ],
            options={
                'verbose_name': 'Элемент комплектации',
                'verbose_name_plural': 'Элементы комплектации',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='game_kit',
        ),
        migrations.AddField(
            model_name='product',
            name='game_kit_items',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.gamekititem', verbose_name='Элементы комплектации'),
        ),
    ]
