# Generated by Django 5.2 on 2025-09-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_gamekititem_remove_product_game_kit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Введите дополнительную информацию. Каждый новый пункт будет отображаться с новой строки.', null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='product',
            name='game_rules',
            field=models.TextField(blank=True, help_text='Введите правила игры. Каждый новый пункт будет отображаться с новой строки.', null=True, verbose_name='Правила игры'),
        ),
    ]
