# Generated by Django 5.2.5 on 2025-10-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_product_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date_event',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
    ]
